# FUNDING.yml - Juan Moises de la Serna Tuya
# ORCID: 0000-0002-8401-8018 | UNIR

github: []
open_collective: []
ko_fi: []
custom:
  - https://orcid.org/0000-0002-8401-8018
  - https://www.linkedin.com/in/juanmoisesdelaserna/
  - https://www.researchgate.net/profile/Juan_De_La_Serna_Tuya
